<?php

namespace Ordini\Entity\Repository;

/**
 * OrdiniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdiniRepository extends \Doctrine\ORM\EntityRepository
{
}
