<div class="container-fluid">

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotti/latte">cioccolato al latte</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotti/fondente">cioccolato fondente</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotti/fondente-extra">cioccolato fondente extra</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotti/bianco">cioccolato bianco</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

</div>
