<div class="container-fluid">

    <?php foreach($this->lista as $prodotto) { ?>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="<?= $this->url('prodotti/default', ['codice' => $prodotto->getCodice()]) ?>"><?=$prodotto->getNome() ?></a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>
    <?php } ?>

</div>
