<div class="container-fluid">

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="<?= $this->url('prodotti/default', ['codice' => 'latte']) ?>">cioccolato al latte</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="<?= $this->url('prodotti/default', ['codice' => 'fondente']) ?>">cioccolato fondente</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="<?= $this->url('prodotti/default', ['codice' => 'fondente-extra']) ?>">cioccolato fondente extra</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="<?= $this->url('prodotti/default', ['codice' => 'bianco']) ?>">cioccolato bianco</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

</div>
