<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <ul class="list-unstyled">
          <li>
            <a href="">Chi siamo</a>
          </li>
          <li>
            <a href="">Dove siamo</a>
          </li>
          <li>
            <a href="">La filosofia</a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-unstyled">
          <li>
            <a href="">Contatti</a>
          </li>
          <li>
            <a href="">Spedizioni</a>
          </li>
          <li>
            <a href="">Regolamento</a>
          </li>
          </a>
        </ul>
      </div>
      <div class="col-md-4">
        <address>
          <strong>Choco company, Inc.</strong><br>
          Viale delle bontà, 123<br>
          Pordenone, Italy<br>
          <abbr title="Phone">P:</abbr> (123) 456-7890
        </address>
      </div>
    </div>
  </div>
</footer>
