<?php

namespace Prodotti\Entity\Repository;

/**
 * ProdottiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdottiRepository extends \Doctrine\ORM\EntityRepository
{
}
