
<a class="btn btn-primary" href="<?=$this->url('zfcadmin/prodotti/nuovo')?>" role="button">nuovo prodotto</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Codice</th>
            <th>Prodotto</th>
            <th>Categoria</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->lista as $prodotto) { ?>
        <tr>
            <th scope="row"><?=$prodotto->getCodice()?></th>
            <td><?=$prodotto->getNome()?></td>
            <td><?=$prodotto->getCategoria()->getNome()?></td>
            <td><a class="btn btn-default" href="#" role="button">modifica</a></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
