<h2>Nuovo prodotto</h2>

<?=$this->form()->openTag($form);?>

    <?php foreach($this->form->getElements() as $element) { ?>
    <div class="form-group">
        <?php
            echo $this->formLabel($element);
            echo $this->formElement($element);
            echo $this->formElementErrors($element);
         ?>
    </div>
    <?php } ?>


    <button type="submit" class="btn btn-default">Salva dati</button>

<?=$this->form()->closeTag($form);?>
