<h2>Ordina prodotto</h2>

<?php
$this->form->prepare();
echo $this->form()->openTag($form);
?>

    <?php foreach($this->form->getElements() as $element) { ?>
    <div class="form-group">
        <?php
            echo $this->formLabel($element);
            echo $this->formElement($element);
            echo $this->formElementErrors($element);
         ?>
    </div>
    <?php } ?>


    <button type="submit" class="btn btn-default">Completa ordine</button>

<?=$this->form()->closeTag($form);?>
