<div class="container-fluid">
  <div class="row banner-home">
    <div class="col-md-3">
      <img src="https://c2.staticflickr.com/6/5105/5626762538_406270541c_b.jpg">
    </div>
    <div class="col-md-9">
      <h1>Il cioccolato più buono? Lo trovi da noi!</h1>
    </div>
  </div>
  <div class="row">

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotto.php?codice=latte">cioccolato al latte</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><a href="/prodotto.php?codice=fondente">cioccolato fondente</a></div>
        <div class="panel-body">
          <img src="" />
        </div>
      </div>
    </div>

  </div>
</div>
