<?php

namespace Application\Entity\Repository;

/**
 * UtenteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtenteRepository extends \Doctrine\ORM\EntityRepository
{
}
